name = "Potato Pack"
author = "Potatoboy9999"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13327dfa0de4967f85b601fe9ff58f1c4e18bf5982ac6b80be22adbb9b8f9a32"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
