name = "Architectury API (Fabric)"
filename = "architectury-1.8.130-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3222/915/architectury-1.8.130-fabric.jar"
hash-format = "murmur2"
hash = "1930183423"

[update]
[update.curseforge]
file-id = 3222915
project-id = 419697
release-channel = "beta"
