name = "Chat Heads"
filename = "chat_heads-0.2.2+1.16.2.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3177/320/chat_heads-0.2.2+1.16.2.jar"
hash-format = "murmur2"
hash = "2119662655"

[update]
[update.curseforge]
file-id = 3177320
project-id = 407206
release-channel = "beta"
