name = "Clear Despawn (Fabric)"
filename = "cleardespawn-1.16.5-fabric0.30.0-1.1.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3193/561/cleardespawn-1.16.5-fabric0.30.0-1.1.1.jar"
hash-format = "murmur2"
hash = "4086154264"

[update]
[update.curseforge]
file-id = 3193561
project-id = 308793
release-channel = "beta"
