name = "Croptopia [FABRIC/FORGE]"
filename = "Croptopia-1.16.4-5-FABRIC-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3185/124/Croptopia-1.16.4-5-FABRIC-1.2.0.jar"
hash-format = "murmur2"
hash = "2657251832"

[update]
[update.curseforge]
file-id = 3185124
project-id = 415438
release-channel = "beta"
