name = "Fedora"
filename = "fedora-1.1.1-fabric-1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3138/837/fedora-1.1.1-fabric-1.16.4.jar"
hash-format = "murmur2"
hash = "2284789184"

[update]
[update.curseforge]
file-id = 3138837
project-id = 417391
release-channel = "beta"
