name = "Flamingo, oh, oh, oh..."
filename = "Flamingo-oh-oh-oh-1.0.4-MC1.16.3-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3124/604/Flamingo-oh-oh-oh-1.0.4-MC1.16.3-fabric.jar"
hash-format = "murmur2"
hash = "4026161796"

[update]
[update.curseforge]
file-id = 3124604
project-id = 396461
release-channel = "beta"
