name = "Industrial Revolution"
filename = "indrev-1.8.11-BETA.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3215/564/indrev-1.8.11-BETA.jar"
hash-format = "murmur2"
hash = "3563836521"

[update]
[update.curseforge]
file-id = 3215564
project-id = 391708
release-channel = "beta"
