name = "Kibe"
filename = "kibe-1.16.5-1.6.4-BETA.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3222/406/kibe-1.16.5-1.6.4-BETA.jar"
hash-format = "murmur2"
hash = "698489399"

[update]
[update.curseforge]
file-id = 3222406
project-id = 388832
release-channel = "beta"
