name = "Mob Origins"
filename = "moborigins-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3220/972/moborigins-1.2.1.jar"
hash-format = "murmur2"
hash = "1347749221"

[update]
[update.curseforge]
file-id = 3220972
project-id = 449974
release-channel = "beta"
