name = "Name Pain"
filename = "NamePain-1.3.1 Forge-1.16.x.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3100/986/NamePain-1.3.1 Forge-1.16.x.jar"
hash-format = "murmur2"
hash = "1090829796"

[update]
[update.curseforge]
file-id = 3100986
project-id = 366263
release-channel = "beta"
