name = "Netherite Plus Mod"
filename = "netherite-plus-mod-1.4.0-1.16.5-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3227/860/netherite-plus-mod-1.4.0-1.16.5-fabric.jar"
hash-format = "murmur2"
hash = "1655925310"

[update]
[update.curseforge]
file-id = 3227860
project-id = 394120
release-channel = "beta"
