name = "Origins"
filename = "Origins-1.16.5-0.5.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3220/828/Origins-1.16.5-0.5.2.jar"
hash-format = "murmur2"
hash = "3257763118"

[update]
[update.curseforge]
file-id = 3220828
project-id = 391943
release-channel = "beta"
