name = "True Secret Rooms"
filename = "true-secret-rooms-1.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3194/197/true-secret-rooms-1.1.3.jar"
hash-format = "murmur2"
hash = "1074917217"

[update]
[update.curseforge]
file-id = 3194197
project-id = 413207
release-channel = "beta"
